version: '3.8'

services:
  spring-api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DD_AGENT_HOST=datadog-agent
      - DD_TRACE_AGENT_PORT=8126
    ports:
      - "8080:8080"
    depends_on:
      - datadog-agent
    networks:
      - app-network

  datadog-agent:
    image: datadog/agent:latest
    environment:
      - DD_API_KEY=your-datadog-api-key
    ports:
      - "8125:8125/udp"
      - "8126:8126/tcp"
    networks:
      - app-network

networks:
  app-network:
