name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # main 브랜치에 푸시할 때마다 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Create SSH directory
      run: mkdir -p ~/.ssh

    - name: Add SSH key
      run: echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}

    - name: Set SSH key permissions
      run: chmod 600 ~/.ssh/id_rsa

    - name: Add SSH config
      run: |
        echo "Host *" > ~/.ssh/config
        echo "    StrictHostKeyChecking no" >> ~/.ssh/config
        echo "    UserKnownHostsFile=/dev/null" >> ~/.ssh/config

    - name: Copy JAR to Bastion Host
      run: |
        scp -i ~/.ssh/id_rsa build/libs/member-0.0.1-SNAPSHOT.jar ${{ secrets.BASTION_USER }}@${{ secrets.BASTION_HOST }}:/tmp/member-0.0.1-SNAPSHOT.jar
        ssh -i ~/.ssh/id_rsa ${{ secrets.BASTION_USER }}@${{ secrets.BASTION_HOST }} "ls -l /tmp/member-0.0.1-SNAPSHOT.jar"

    - name: Transfer JAR from Bastion to Private EC2
      run: |
        scp -i ~/.ssh/id_rsa -o "ProxyCommand ssh -i ~/.ssh/id_rsa -W %h:%p ${{ secrets.BASTION_USER }}@${{ secrets.BASTION_HOST }}" /tmp/member-0.0.1-SNAPSHOT.jar ${{ secrets.EC2_USER }}@${{ secrets.PRIVATE_EC2_HOST }}:/home/ec2-user/
        ssh -i ~/.ssh/id_rsa ${{ secrets.BASTION_USER }}@${{ secrets.BASTION_HOST }} "rm /tmp/member-0.0.1-SNAPSHOT.jar"

    - name: SSH and Run Application on Private EC2
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.PRIVATE_EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          export SPRING_DATASOURCE_URL=jdbc:mysql://jhs-db-instance-1.coxwo6u60is7.ap-northeast-2.rds.amazonaws.com:3306/myapp
          export SPRING_DATASOURCE_USERNAME=admin
          export SPRING_DATASOURCE_PASSWORD=password
          nohup java -jar /home/ec2-user/member-0.0.1-SNAPSHOT.jar > /dev/null 2>&1 &
