name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # main 브랜치에 푸시할 때마다 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Copy JAR to Bastion Host
      uses: appleboy/scp-action@v0.1.5
      with:
        host: ${{ secrets.BASTION_HOST }}
        username: ${{ secrets.BASTION_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        source: "build/libs/member-0.0.1-SNAPSHOT.jar"
        target: "/tmp/member-0.0.1-SNAPSHOT.jar"

    - name: Transfer JAR from Bastion to Private EC2
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.BASTION_HOST }}
        username: ${{ secrets.BASTION_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          scp -i ~/.ssh/id_rsa -o "ProxyCommand ssh -i ~/.ssh/id_rsa -W %h:%p ${{ secrets.BASTION_USER }}@${{ secrets.BASTION_HOST }}" /tmp/member-0.0.1-SNAPSHOT.jar ${{ secrets.EC2_USER }}@${{ secrets.PRIVATE_EC2_HOST }}:/home/ec2-user/
          rm /tmp/member-0.0.1-SNAPSHOT.jar
